#!/usr/bin/env sh

cp -f dist/dnsmasq.conf /etc/dnsmasq.d/
cp -f dist/hosts.conf /etc/

/etc/init.d/dnsmasq force-reload

sftp admin@192.168.88.1 <<EOF
put dist/router.rules
EOF

ssh admin@192.168.88.1 "/import router.rules"