#!/usr/bin/env ruby

require 'resolv'
require 'json'

log_file      = 'dnsmasq.log'
sites_file    = 'conf/sites.conf'
hosts_file    = 'dist/dnsmasq/address.conf'
dnsmasq_file  = 'dist/dnsmasq/server.conf'
domains_file  = 'dist/domains.list'
rules_file    = 'dist/router.rules'
open_dns_ip   = '208.67.222.222'
open_dns_port = 443

# download dnsmasq log
system 'scp pi@192.168.88.242:/var/log/dnsmasq.log .'

log_rows = File.read log_file
sites = File.read(sites_file)
            .split("\n")
            .select { |site| !(site.include? '#' or site.empty? ) }

# update dnsmasq resolv file
File.open(dnsmasq_file, 'w') do |file|
  sites.each do |site|
    file.write "server=/#{site}/#{open_dns_ip}##{open_dns_port}\n"
  end
end

# update domain ip list
keyword = ': forwarded'
domains = File.read(domains_file).split("\n")
log_rows.each_line do |line|
  line.strip!
  next unless line.include? keyword
  sites.each do |site|
    if line.include? "#{site} "
      index = line.index(' to ') + 4
      reply = line[index..-1]
      if reply =~ /\d+\.\d+\.\d+\./
        domain_start = line.index(keyword) + keyword.length
        domain_end   = reply.length + 5
        domain_name  = line[domain_start..-domain_end].strip!
        domains.push domain_name
      end
      break
    end
  end
end

domains.uniq!.sort_by! do |a, b|
  a = a.split('.')[-2] unless a.nil?
  b = b.split('.')[-2] unless b.nil?
  a <=> b
end

# update domains file
File.open(domains_file, 'w') do |file|
  file.write domains.join("\n")
end

# update DNS result
dns_server = Resolv::DNS.new nameserver_port: [[open_dns_ip, open_dns_port]]
hosts = {}
domains.each do |domain|
  p "resolving #{domain}"
  begin
    hosts[domain] = dns_server.getaddress(domain).to_s
  rescue => detail
    p "resolving #{domain} fail: #{detail}"
  end
end

# update host file
File.open(hosts_file, 'w') do |file|
  hosts.each do |h|
    file.write "address=/#{h[0]}/#{h[1]}\n"
  end
end

# update dnsmasq file
File.open(rules_file, 'w') do |file|
  hosts.each do |h|
    file.write "/ip route remove [/ip route find dst-address=#{h[1]}/32]\n"
    file.write "/ip route add dst-address=#{h[1]}/32 gateway=pptp-out1 comment=gfw\n"
  end
end
