#!/usr/bin/env ruby

require 'resolv'
require 'json'

log_file      = 'dnsmasq.log'
sites_file    = 'conf/sites.conf'
host_file     = 'dist/hosts.conf'
rules_file    = 'dist/router.rules'
domains_file  = 'dist/domains.conf'
dnsmasq_file  = 'dist/dnsmasq.conf'
open_dns_ip   = '208.67.222.222'
open_dns_port = '443'

# download dnsmasq log
system 'scp pi@192.168.88.242:/var/log/dnsmasq.log .'

log_rows = File.read log_file
# File.truncate log_file, 0
sites = File.read(sites_file)
            .split("\n")
            .select { |site| !(site.include? '#' or site.empty? ) }

# update dnsmasq resolv file
File.open(dnsmasq_file, 'w') do |file|
  sites.each do |site|
    file.write "server=/#{site}/#{open_dns_ip}##{open_dns_port}\n"
  end
end

# update domain ip list
keyword = ': reply'
domains = File.read(domains_file).split("\n")
log_rows.each_line do |line|
  line.strip!
  next unless line.include? keyword
  sites.each do |site|
    if line.include? "#{site} "
      index = line.index(' is ') + 4
      reply = line[index..-1]
      if reply =~ /\d+\.\d+\.\d+\./
        domain_start = line.index(keyword) + keyword.length
        domain_end   = reply.length + 5
        domain_name  = line[domain_start..-domain_end].strip!
        domains.push domain_name
      end
      break
    end
  end
end

domains.uniq!.sort!

# update domains file
File.open(domains_file, 'w') do |file|
  file.write domains.join("\n")
end

# update DNS result
dns_server = Resolv::DNS.new(:nameserver_port => [open_dns_ip, open_dns_port])
hosts = {}
domains.each do |domain|
  p "resolving #{domain}"
  dns_server.each_address(domain) do |ip|
    hosts[ip.to_s] = domain
  end
end

# update host file
File.open(host_file, 'w') do |file|
  hosts.each do |h|
    file.write "#{h[0]} #{h[1]}\n"
  end
end

# update dnsmasq file
File.open(rules_file, 'w') do |file|
  hosts.each do |h|
    file.write "/ip route remove [/ip route find dst-address=#{h[0]}/32]\n"
    file.write "/ip route add dst-address=#{h[0]}/32 gateway=pptp-out1 comment=\"gfw\"\n"
  end
end
